"""Image SQLAlchemy model."""

import uuid
from datetime import UTC, datetime
from typing import TYPE_CHECKING

from sqlalchemy import DateTime, ForeignKey, Integer, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base

if TYPE_CHECKING:
    from app.models.tag import ImageTag


def generate_uuid() -> str:
    """Generate a new UUID string."""
    return str(uuid.uuid4())


def utc_now() -> datetime:
    """Get current UTC timestamp."""
    return datetime.now(UTC)


class Image(Base):
    """Image metadata model."""

    __tablename__ = "images"

    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=generate_uuid,
    )
    filename: Mapped[str] = mapped_column(String(255), nullable=False)
    storage_key: Mapped[str] = mapped_column(String(255), unique=True, nullable=False)
    content_type: Mapped[str] = mapped_column(String(100), nullable=False)
    file_size: Mapped[int] = mapped_column(Integer, nullable=False)
    upload_ip: Mapped[str] = mapped_column(String(45), nullable=False)  # IPv6 max length
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=utc_now,
        nullable=False,
    )
    # Phase 1.5: Image dimensions (nullable for backward compatibility)
    width: Mapped[int | None] = mapped_column(Integer, nullable=True)
    height: Mapped[int | None] = mapped_column(Integer, nullable=True)

    # Phase 2A: User ownership (nullable for anonymous uploads)
    user_id: Mapped[str | None] = mapped_column(
        String(36), ForeignKey("users.id"), nullable=True, index=True
    )
    # Delete token hash for anonymous uploads (SHA-256 hash, not plaintext)
    delete_token_hash: Mapped[str | None] = mapped_column(String(64), nullable=True)

    # Phase 2B: Thumbnail storage key (null until generated by background task)
    thumbnail_key: Mapped[str | None] = mapped_column(String(255), nullable=True)

    # Relationships
    image_tags: Mapped[list["ImageTag"]] = relationship(  # type: ignore[name-defined]
        "ImageTag",
        back_populates="image",
        cascade="all, delete-orphan",
    )

    def __repr__(self) -> str:
        return f"<Image(id={self.id}, filename={self.filename})>"
