"""add_users_table_and_image_ownership

Revision ID: 2f6a8fb30700
Revises: a11aa549249d
Create Date: 2026-01-02 23:16:14.449736

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f6a8fb30700"
down_revision: str | Sequence[str] | None = "a11aa549249d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.add_column("images", sa.Column("user_id", sa.String(length=36), nullable=True))
    op.add_column("images", sa.Column("delete_token_hash", sa.String(length=64), nullable=True))
    op.create_index(op.f("ix_images_user_id"), "images", ["user_id"], unique=False)
    op.create_foreign_key(None, "images", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "images", type_="foreignkey")
    op.drop_index(op.f("ix_images_user_id"), table_name="images")
    op.drop_column("images", "delete_token_hash")
    op.drop_column("images", "user_id")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
